/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VardRouteImport } from './routes/vard'
import { Route as SokRouteImport } from './routes/sok'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as MinaBokningarRouteImport } from './routes/mina-bokningar'
import { Route as LoggaInRouteImport } from './routes/logga-in'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as HyrUtRouteImport } from './routes/hyr-ut'
import { Route as HurDetFunkarRouteImport } from './routes/hur-det-funkar'
import { Route as AterstallLosenordRouteImport } from './routes/aterstall-losenord'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VardFakturaRouteImport } from './routes/vard.faktura'
import { Route as VardBokningarRouteImport } from './routes/vard.bokningar'
import { Route as StugaSlugRouteImport } from './routes/stuga.$slug'
import { Route as OmradeSlugRouteImport } from './routes/omrade.$slug'
import { Route as VardStugorNyRouteImport } from './routes/vard.stugor.ny'
import { Route as VardStugorIdRedigeraRouteImport } from './routes/vard.stugor.$id.redigera'

const VardRoute = VardRouteImport.update({
  id: '/vard',
  path: '/vard',
  getParentRoute: () => rootRouteImport,
} as any)
const SokRoute = SokRouteImport.update({
  id: '/sok',
  path: '/sok',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const MinaBokningarRoute = MinaBokningarRouteImport.update({
  id: '/mina-bokningar',
  path: '/mina-bokningar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const HyrUtRoute = HyrUtRouteImport.update({
  id: '/hyr-ut',
  path: '/hyr-ut',
  getParentRoute: () => rootRouteImport,
} as any)
const HurDetFunkarRoute = HurDetFunkarRouteImport.update({
  id: '/hur-det-funkar',
  path: '/hur-det-funkar',
  getParentRoute: () => rootRouteImport,
} as any)
const AterstallLosenordRoute = AterstallLosenordRouteImport.update({
  id: '/aterstall-losenord',
  path: '/aterstall-losenord',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VardFakturaRoute = VardFakturaRouteImport.update({
  id: '/faktura',
  path: '/faktura',
  getParentRoute: () => VardRoute,
} as any)
const VardBokningarRoute = VardBokningarRouteImport.update({
  id: '/bokningar',
  path: '/bokningar',
  getParentRoute: () => VardRoute,
} as any)
const StugaSlugRoute = StugaSlugRouteImport.update({
  id: '/stuga/$slug',
  path: '/stuga/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OmradeSlugRoute = OmradeSlugRouteImport.update({
  id: '/omrade/$slug',
  path: '/omrade/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VardStugorNyRoute = VardStugorNyRouteImport.update({
  id: '/stugor/ny',
  path: '/stugor/ny',
  getParentRoute: () => VardRoute,
} as any)
const VardStugorIdRedigeraRoute = VardStugorIdRedigeraRouteImport.update({
  id: '/stugor/$id/redigera',
  path: '/stugor/$id/redigera',
  getParentRoute: () => VardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/hur-det-funkar': typeof HurDetFunkarRoute
  '/hyr-ut': typeof HyrUtRoute
  '/kontakt': typeof KontaktRoute
  '/konto': typeof KontoRoute
  '/logga-in': typeof LoggaInRoute
  '/mina-bokningar': typeof MinaBokningarRoute
  '/om-oss': typeof OmOssRoute
  '/sok': typeof SokRoute
  '/vard': typeof VardRouteWithChildren
  '/omrade/$slug': typeof OmradeSlugRoute
  '/stuga/$slug': typeof StugaSlugRoute
  '/vard/bokningar': typeof VardBokningarRoute
  '/vard/faktura': typeof VardFakturaRoute
  '/vard/stugor/ny': typeof VardStugorNyRoute
  '/vard/stugor/$id/redigera': typeof VardStugorIdRedigeraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/hur-det-funkar': typeof HurDetFunkarRoute
  '/hyr-ut': typeof HyrUtRoute
  '/kontakt': typeof KontaktRoute
  '/konto': typeof KontoRoute
  '/logga-in': typeof LoggaInRoute
  '/mina-bokningar': typeof MinaBokningarRoute
  '/om-oss': typeof OmOssRoute
  '/sok': typeof SokRoute
  '/vard': typeof VardRouteWithChildren
  '/omrade/$slug': typeof OmradeSlugRoute
  '/stuga/$slug': typeof StugaSlugRoute
  '/vard/bokningar': typeof VardBokningarRoute
  '/vard/faktura': typeof VardFakturaRoute
  '/vard/stugor/ny': typeof VardStugorNyRoute
  '/vard/stugor/$id/redigera': typeof VardStugorIdRedigeraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/hur-det-funkar': typeof HurDetFunkarRoute
  '/hyr-ut': typeof HyrUtRoute
  '/kontakt': typeof KontaktRoute
  '/konto': typeof KontoRoute
  '/logga-in': typeof LoggaInRoute
  '/mina-bokningar': typeof MinaBokningarRoute
  '/om-oss': typeof OmOssRoute
  '/sok': typeof SokRoute
  '/vard': typeof VardRouteWithChildren
  '/omrade/$slug': typeof OmradeSlugRoute
  '/stuga/$slug': typeof StugaSlugRoute
  '/vard/bokningar': typeof VardBokningarRoute
  '/vard/faktura': typeof VardFakturaRoute
  '/vard/stugor/ny': typeof VardStugorNyRoute
  '/vard/stugor/$id/redigera': typeof VardStugorIdRedigeraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aterstall-losenord'
    | '/hur-det-funkar'
    | '/hyr-ut'
    | '/kontakt'
    | '/konto'
    | '/logga-in'
    | '/mina-bokningar'
    | '/om-oss'
    | '/sok'
    | '/vard'
    | '/omrade/$slug'
    | '/stuga/$slug'
    | '/vard/bokningar'
    | '/vard/faktura'
    | '/vard/stugor/ny'
    | '/vard/stugor/$id/redigera'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aterstall-losenord'
    | '/hur-det-funkar'
    | '/hyr-ut'
    | '/kontakt'
    | '/konto'
    | '/logga-in'
    | '/mina-bokningar'
    | '/om-oss'
    | '/sok'
    | '/vard'
    | '/omrade/$slug'
    | '/stuga/$slug'
    | '/vard/bokningar'
    | '/vard/faktura'
    | '/vard/stugor/ny'
    | '/vard/stugor/$id/redigera'
  id:
    | '__root__'
    | '/'
    | '/aterstall-losenord'
    | '/hur-det-funkar'
    | '/hyr-ut'
    | '/kontakt'
    | '/konto'
    | '/logga-in'
    | '/mina-bokningar'
    | '/om-oss'
    | '/sok'
    | '/vard'
    | '/omrade/$slug'
    | '/stuga/$slug'
    | '/vard/bokningar'
    | '/vard/faktura'
    | '/vard/stugor/ny'
    | '/vard/stugor/$id/redigera'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AterstallLosenordRoute: typeof AterstallLosenordRoute
  HurDetFunkarRoute: typeof HurDetFunkarRoute
  HyrUtRoute: typeof HyrUtRoute
  KontaktRoute: typeof KontaktRoute
  KontoRoute: typeof KontoRoute
  LoggaInRoute: typeof LoggaInRoute
  MinaBokningarRoute: typeof MinaBokningarRoute
  OmOssRoute: typeof OmOssRoute
  SokRoute: typeof SokRoute
  VardRoute: typeof VardRouteWithChildren
  OmradeSlugRoute: typeof OmradeSlugRoute
  StugaSlugRoute: typeof StugaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vard': {
      id: '/vard'
      path: '/vard'
      fullPath: '/vard'
      preLoaderRoute: typeof VardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sok': {
      id: '/sok'
      path: '/sok'
      fullPath: '/sok'
      preLoaderRoute: typeof SokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mina-bokningar': {
      id: '/mina-bokningar'
      path: '/mina-bokningar'
      fullPath: '/mina-bokningar'
      preLoaderRoute: typeof MinaBokningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyr-ut': {
      id: '/hyr-ut'
      path: '/hyr-ut'
      fullPath: '/hyr-ut'
      preLoaderRoute: typeof HyrUtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hur-det-funkar': {
      id: '/hur-det-funkar'
      path: '/hur-det-funkar'
      fullPath: '/hur-det-funkar'
      preLoaderRoute: typeof HurDetFunkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aterstall-losenord': {
      id: '/aterstall-losenord'
      path: '/aterstall-losenord'
      fullPath: '/aterstall-losenord'
      preLoaderRoute: typeof AterstallLosenordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vard/faktura': {
      id: '/vard/faktura'
      path: '/faktura'
      fullPath: '/vard/faktura'
      preLoaderRoute: typeof VardFakturaRouteImport
      parentRoute: typeof VardRoute
    }
    '/vard/bokningar': {
      id: '/vard/bokningar'
      path: '/bokningar'
      fullPath: '/vard/bokningar'
      preLoaderRoute: typeof VardBokningarRouteImport
      parentRoute: typeof VardRoute
    }
    '/stuga/$slug': {
      id: '/stuga/$slug'
      path: '/stuga/$slug'
      fullPath: '/stuga/$slug'
      preLoaderRoute: typeof StugaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omrade/$slug': {
      id: '/omrade/$slug'
      path: '/omrade/$slug'
      fullPath: '/omrade/$slug'
      preLoaderRoute: typeof OmradeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vard/stugor/ny': {
      id: '/vard/stugor/ny'
      path: '/stugor/ny'
      fullPath: '/vard/stugor/ny'
      preLoaderRoute: typeof VardStugorNyRouteImport
      parentRoute: typeof VardRoute
    }
    '/vard/stugor/$id/redigera': {
      id: '/vard/stugor/$id/redigera'
      path: '/stugor/$id/redigera'
      fullPath: '/vard/stugor/$id/redigera'
      preLoaderRoute: typeof VardStugorIdRedigeraRouteImport
      parentRoute: typeof VardRoute
    }
  }
}

interface VardRouteChildren {
  VardBokningarRoute: typeof VardBokningarRoute
  VardFakturaRoute: typeof VardFakturaRoute
  VardStugorNyRoute: typeof VardStugorNyRoute
  VardStugorIdRedigeraRoute: typeof VardStugorIdRedigeraRoute
}

const VardRouteChildren: VardRouteChildren = {
  VardBokningarRoute: VardBokningarRoute,
  VardFakturaRoute: VardFakturaRoute,
  VardStugorNyRoute: VardStugorNyRoute,
  VardStugorIdRedigeraRoute: VardStugorIdRedigeraRoute,
}

const VardRouteWithChildren = VardRoute._addFileChildren(VardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AterstallLosenordRoute: AterstallLosenordRoute,
  HurDetFunkarRoute: HurDetFunkarRoute,
  HyrUtRoute: HyrUtRoute,
  KontaktRoute: KontaktRoute,
  KontoRoute: KontoRoute,
  LoggaInRoute: LoggaInRoute,
  MinaBokningarRoute: MinaBokningarRoute,
  OmOssRoute: OmOssRoute,
  SokRoute: SokRoute,
  VardRoute: VardRouteWithChildren,
  OmradeSlugRoute: OmradeSlugRoute,
  StugaSlugRoute: StugaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
